export const CITIES = [
  {
    slug: 'delhi',
    name: 'Delhi / NCR',
    state: 'Delhi',
    shortName: 'Delhi',
    multiplier: 1.25,
    population: '3.2 Cr+',
    projectCount: 32,
    avgCost: '₹2,100–₹3,600',
    landmark: 'India Gate',
    about: 'Delhi NCR is one of India\'s most active construction markets. With rapid urbanisation across Gurgaon, Noida, Faridabad, and Ghaziabad, demand for quality residential and commercial construction has never been higher. BuildRight has completed 32 projects across the NCR region.',
    popular: ['Luxury Villas', 'Commercial Complexes', 'Builder Floors', 'Office Spaces'],
    areas: ['South Delhi', 'Dwarka', 'Noida', 'Gurgaon', 'Faridabad', 'Ghaziabad'],
    testimonial: { name: 'Rajesh Sharma', text: 'BuildRight built our South Delhi home with exceptional quality. Delivered 10 days ahead of schedule.', project: '2,800 sq ft Residence' },
  },
  {
    slug: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    shortName: 'Mumbai',
    multiplier: 1.35,
    population: '2 Cr+',
    projectCount: 18,
    avgCost: '₹2,400–₹4,200',
    landmark: 'Gateway of India',
    about: 'Mumbai\'s premium real estate market demands the highest standards of construction quality. From Thane to Navi Mumbai, our team has delivered 18 projects that meet Mumbai\'s stringent building regulations and premium expectations.',
    popular: ['High-Rise Apartments', 'Commercial Offices', 'Retail Showrooms', 'Renovations'],
    areas: ['Thane', 'Navi Mumbai', 'Andheri', 'Borivali', 'Kalyan', 'Dombivli'],
    testimonial: { name: 'Priya Mehta', text: 'Outstanding quality and they handled all the BMC approvals seamlessly. Highly recommended.', project: '4,500 sq ft Office' },
  },
  {
    slug: 'bangalore',
    name: 'Bangalore',
    state: 'Karnataka',
    shortName: 'Bangalore',
    multiplier: 1.20,
    population: '1.3 Cr+',
    projectCount: 24,
    avgCost: '₹2,200–₹3,800',
    landmark: 'Vidhana Soudha',
    about: 'Bangalore\'s booming IT sector drives demand for modern commercial spaces and premium homes. Our team is well-versed in BBMP regulations and has delivered 24 projects across Whitefield, Electronic City, and North Bangalore.',
    popular: ['Tech Office Campuses', 'Villa Communities', 'Commercial Complexes', 'Modern Homes'],
    areas: ['Whitefield', 'Electronic City', 'Hebbal', 'Sarjapur', 'JP Nagar', 'Yelahanka'],
    testimonial: { name: 'Anand Kumar', text: 'Built our tech startup\'s office with great attention to detail. Team was always on time.', project: '6,000 sq ft Office Campus' },
  },
  {
    slug: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    shortName: 'Pune',
    multiplier: 1.15,
    population: '70 L+',
    projectCount: 21,
    avgCost: '₹2,000–₹3,400',
    landmark: 'Shaniwar Wada',
    about: 'Pune\'s expanding IT and manufacturing corridors have made it one of Maharashtra\'s fastest-growing construction markets. With 21 completed projects, BuildRight is a trusted name for quality construction in Pune and the surrounding Pimpri-Chinchwad area.',
    popular: ['IT Park Construction', 'Residential Townships', 'Commercial Plazas', 'Warehouses'],
    areas: ['Hinjewadi', 'Kharadi', 'Baner', 'Wakad', 'Hadapsar', 'Pimpri-Chinchwad'],
    testimonial: { name: 'Sunita Patil', text: 'They completed our commercial plaza in Hinjewadi well within budget. Great team.', project: '12,000 sq ft Commercial Hub' },
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    shortName: 'Hyderabad',
    multiplier: 1.10,
    population: '1 Cr+',
    projectCount: 15,
    avgCost: '₹1,900–₹3,200',
    landmark: 'Charminar',
    about: 'Hyderabad\'s HITEC City corridor and Outer Ring Road developments have created tremendous construction demand. Our 15 projects in Hyderabad span luxury villas in Jubilee Hills to commercial complexes in Gachibowli.',
    popular: ['Luxury Villas', 'Commercial IT Spaces', 'Residential Apartments', 'Retail Outlets'],
    areas: ['Gachibowli', 'HITEC City', 'Jubilee Hills', 'Kondapur', 'Miyapur', 'LB Nagar'],
    testimonial: { name: 'Vijay Reddy', text: 'Our Gachibowli office was built to perfection. The team understood our vision completely.', project: '8,000 sq ft IT Office' },
  },
  {
    slug: 'indore',
    name: 'Indore',
    state: 'Madhya Pradesh',
    shortName: 'Indore',
    multiplier: 1.00,
    population: '35 L+',
    projectCount: 28,
    avgCost: '₹1,700–₹2,900',
    landmark: 'Rajwada Palace',
    about: 'Indore — India\'s cleanest city — is our home base and strongest market. With 28 projects completed, we know Indore\'s construction landscape inside out, from Vijay Nagar\'s residential colonies to the AB Road commercial corridor.',
    popular: ['Independent Houses', 'Commercial Shops', 'Showrooms', 'Renovations'],
    areas: ['Vijay Nagar', 'Scheme 78', 'Super Corridor', 'Bicholi', 'Rajendra Nagar', 'Palasia'],
    testimonial: { name: 'Suresh Verma', text: 'Our Vijay Nagar villa was delivered 12 days early. Couldn\'t be happier with the quality.', project: '3,200 sq ft Villa' },
  },
  {
    slug: 'bhopal',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    shortName: 'Bhopal',
    multiplier: 0.98,
    population: '25 L+',
    projectCount: 19,
    avgCost: '₹1,600–₹2,700',
    landmark: 'Upper Lake',
    about: 'Bhopal\'s growing economy and government infrastructure push have created strong construction demand. Our 19 projects in Bhopal include everything from residential colonies in Arera Colony to commercial complexes on MP Nagar.',
    popular: ['Government Projects', 'Residential Homes', 'Commercial Shops', 'School Buildings'],
    areas: ['Arera Colony', 'MP Nagar', 'Kolar Road', 'Ayodhya Bypass', 'Hoshangabad Road', 'TT Nagar'],
    testimonial: { name: 'Ramesh Gupta', text: 'All 24 units of our shopping centre were rented within 2 months of handover. Exceptional work.', project: '6,400 sq ft Shopping Centre' },
  },
  {
    slug: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    shortName: 'Jaipur',
    multiplier: 1.00,
    population: '40 L+',
    projectCount: 12,
    avgCost: '₹1,700–₹2,900',
    landmark: 'Hawa Mahal',
    about: 'Jaipur\'s Pink City heritage combined with modern development has created a unique construction market. Our 12 Jaipur projects blend traditional Rajasthani aesthetics with modern structural standards, from Vaishali Nagar homes to Tonk Road commercial developments.',
    popular: ['Heritage-Style Homes', 'Commercial Complexes', 'Hotel Construction', 'Residential Villas'],
    areas: ['Vaishali Nagar', 'Malviya Nagar', 'Tonk Road', 'Mansarovar', 'C-Scheme', 'Jagatpura'],
    testimonial: { name: 'Deepak Kapoor', text: 'All 24 apartments in our complex sold before completion. BuildRight delivered excellence.', project: '18,000 sq ft Residential Complex' },
  },
  {
    slug: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    shortName: 'Ahmedabad',
    multiplier: 1.05,
    population: '85 L+',
    projectCount: 14,
    avgCost: '₹1,800–₹3,000',
    landmark: 'Sabarmati Ashram',
    about: 'Ahmedabad\'s business-first culture and Gujarat\'s industrial growth make it a thriving construction market. Our 14 projects span the GIFT City corridor, SG Highway showrooms, and South Bopal residential developments.',
    popular: ['Industrial Warehouses', 'Showrooms', 'Commercial Offices', 'Residential Bungalows'],
    areas: ['GIFT City', 'SG Highway', 'Prahlad Nagar', 'South Bopal', 'Thaltej', 'Chandkheda'],
    testimonial: { name: 'Kiran Patel', text: 'Our auto showroom glass facade is exactly what we envisioned. Delivered in just 10 months.', project: '5,200 sq ft Auto Showroom' },
  },
  {
    slug: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    shortName: 'Lucknow',
    multiplier: 0.97,
    population: '40 L+',
    projectCount: 11,
    avgCost: '₹1,550–₹2,600',
    landmark: 'Bara Imambara',
    about: 'Lucknow\'s Gomti Nagar and upcoming expressway developments are driving strong construction demand. Our 11 projects in the City of Nawabs demonstrate that nawabi taste can meet modern construction standards and timelines.',
    popular: ['Independent Houses', 'Commercial Shops', 'Renovations', 'Government Buildings'],
    areas: ['Gomti Nagar', 'Hazratganj', 'Aliganj', 'Indira Nagar', 'Vikas Nagar', 'Kanpur Road'],
    testimonial: { name: 'Amarjit Singh', text: 'Our 20-year-old house was completely transformed in just 5 months. Incredible work.', project: '1,800 sq ft Full Renovation' },
  },
  {
    slug: 'nagpur',
    name: 'Nagpur',
    state: 'Maharashtra',
    shortName: 'Nagpur',
    multiplier: 0.97,
    population: '30 L+',
    projectCount: 9,
    avgCost: '₹1,550–₹2,600',
    landmark: 'Deekshabhoomi',
    about: 'Nagpur\'s central location and MIHAN project developments make it a growing construction hub. As Maharashtra\'s second capital develops rapidly, our 9 Nagpur projects reflect our commitment to quality across all tier-2 markets.',
    popular: ['Residential Homes', 'Commercial Offices', 'MIHAN Zone Facilities', 'Retail Outlets'],
    areas: ['Civil Lines', 'Dharampeth', 'Bajaj Nagar', 'Manish Nagar', 'MIHAN', 'Wardha Road'],
    testimonial: { name: 'Prashant Deshpande', text: 'Honest pricing and quality that speaks for itself. Our home was worth every rupee.', project: '2,200 sq ft Home' },
  },
  {
    slug: 'surat',
    name: 'Surat',
    state: 'Gujarat',
    shortName: 'Surat',
    multiplier: 1.02,
    population: '70 L+',
    projectCount: 8,
    avgCost: '₹1,750–₹2,900',
    landmark: 'Surat Castle',
    about: 'Surat — India\'s diamond and textile capital — has a booming construction market driven by business wealth. Our 8 Surat projects reflect the city\'s preference for quality, efficient timelines, and value for money.',
    popular: ['Commercial Showrooms', 'Textile Factory Construction', 'Residential Bungalows', 'Office Spaces'],
    areas: ['Adajan', 'Vesu', 'Pal', 'Althan', 'Katargam', 'Udhna'],
    testimonial: { name: 'Hitesh Shah', text: 'Fast, quality, and honest. Exactly what Surat businessmen need. Highly recommend.', project: '3,800 sq ft Commercial Space' },
  },
];

export const CITY_SLUGS = CITIES.map(c => c.slug);

export function getCityBySlug(slug) {
  return CITIES.find(c => c.slug === slug) || null;
}