export const PROJECTS = [
  {
    slug: 'sharma-residence-delhi',
    title: 'Sharma Residence',
    location: 'New Delhi',
    city: 'delhi',
    type: 'residential',
    typeLabel: 'Residential',
    area: 2800,
    budget: '₹1.2 Cr',
    duration: '14 months',
    quality: 'Premium',
    year: 2024,
    status: 'completed',
    rating: 5,
    color: '#C8891A',
    client: 'Rajesh Sharma',
    desc: 'A luxurious 4BHK independent home with vastu-compliant layout, Italian marble flooring, and a rooftop garden. Delivered 10 days ahead of schedule.',
    highlights: ['4 BHK + Study Room', 'Rooftop Garden', 'Italian Marble Flooring', 'Home Automation', 'Double Height Living Room'],
    testimonial: 'BuildRight delivered beyond our expectations. The attention to detail and quality of materials is exceptional.',
  },
  {
    slug: 'sunrise-commercial-pune',
    title: 'Sunrise Commercial Hub',
    location: 'Pune',
    city: 'pune',
    type: 'commercial',
    typeLabel: 'Commercial',
    area: 12000,
    budget: '₹4.8 Cr',
    duration: '22 months',
    quality: 'Premium',
    year: 2024,
    status: 'completed',
    rating: 5,
    color: '#4A7C59',
    client: 'Sunrise Ventures Pvt Ltd',
    desc: 'A 5-storey commercial complex with ground floor retail, 3 office floors, and a rooftop cafeteria. RERA registered and fully compliant.',
    highlights: ['5 Storeys', 'Ground Floor Retail', 'Glass Facade', 'Rooftop Cafeteria', 'Underground Parking'],
    testimonial: 'Professional team, transparent billing, and superb quality. Our complex was completed on budget.',
  },
  {
    slug: 'gupta-shopping-bhopal',
    title: 'Gupta Shopping Centre',
    location: 'Bhopal',
    city: 'bhopal',
    type: 'retail',
    typeLabel: 'Retail',
    area: 6400,
    budget: '₹2.1 Cr',
    duration: '18 months',
    quality: 'Standard',
    year: 2023,
    status: 'completed',
    rating: 5,
    color: '#5B6FA6',
    client: 'Gupta Brothers',
    desc: 'A modern shopping centre with 24 retail units, wide corridors, ample parking, and an attractive street-facing facade.',
    highlights: ['24 Retail Units', 'Wide Corridors', '80-car Parking', 'LED Facade Lighting', 'Fire Safety Certified'],
    testimonial: 'All 24 units were rented within 2 months of completion. The quality speaks for itself.',
  },
  {
    slug: 'verma-villa-indore',
    title: 'Verma Villa',
    location: 'Indore',
    city: 'indore',
    type: 'residential',
    typeLabel: 'Residential',
    area: 3200,
    budget: '₹1.6 Cr',
    duration: '16 months',
    quality: 'Premium',
    year: 2023,
    status: 'completed',
    rating: 5,
    color: '#9B6B9B',
    client: 'Suresh Verma',
    desc: 'An elegant villa with contemporary architecture, a private pool, landscaped garden, and smart home integration throughout.',
    highlights: ['Private Pool', 'Smart Home System', 'Landscaped Garden', 'Modular Kitchen', 'Solar Panels'],
    testimonial: 'My dream home, delivered 12 days early. The team was professional and communicative throughout.',
  },
  {
    slug: 'mehta-office-bangalore',
    title: 'Mehta & Associates Office',
    location: 'Bangalore',
    city: 'bangalore',
    type: 'commercial',
    typeLabel: 'Commercial',
    area: 4500,
    budget: '₹1.9 Cr',
    duration: '12 months',
    quality: 'Premium',
    year: 2024,
    status: 'completed',
    rating: 5,
    color: '#C85A3A',
    client: 'Mehta & Associates',
    desc: 'A modern law firm office with open floor plan, private chambers, conference rooms, and a client lounge. Fully soundproofed.',
    highlights: ['Open Floor Plan', '8 Private Chambers', '2 Conference Rooms', 'Soundproofed', 'Client Lounge'],
    testimonial: 'Transformed our workspace completely. Clients are always impressed when they visit.',
  },
  {
    slug: 'patel-showroom-ahmedabad',
    title: 'Patel Auto Showroom',
    location: 'Ahmedabad',
    city: 'ahmedabad',
    type: 'retail',
    typeLabel: 'Retail',
    area: 5200,
    budget: '₹1.7 Cr',
    duration: '10 months',
    quality: 'Standard',
    year: 2023,
    status: 'completed',
    rating: 4,
    color: '#7A6A4A',
    client: 'Patel Automobiles',
    desc: 'A flagship automobile showroom with a glass front, showroom floor for 12 vehicles, service bay, and customer lounge.',
    highlights: ['Glass Front Facade', '12-vehicle Display', 'Service Bay', 'Customer Lounge', 'EV Charging Points'],
    testimonial: 'Delivered fast and clean. The glass facade is exactly what we envisioned.',
  },
  {
    slug: 'singh-home-renovation-lucknow',
    title: 'Singh Home Renovation',
    location: 'Lucknow',
    city: 'lucknow',
    type: 'renovation',
    typeLabel: 'Renovation',
    area: 1800,
    budget: '₹48 L',
    duration: '5 months',
    quality: 'Standard',
    year: 2024,
    status: 'completed',
    rating: 5,
    color: '#4A7A7A',
    client: 'Amarjit Singh',
    desc: 'Complete renovation of a 20-year-old house — new electrical wiring, plumbing, flooring, kitchen, and bathrooms. Transformed entirely.',
    highlights: ['Full Electrical Rewiring', 'New Plumbing', 'Modular Kitchen', '3 New Bathrooms', 'Exterior Plastering'],
    testimonial: "Our old house feels brand new. Couldn't believe the transformation in just 5 months.",
  },
  {
    slug: 'kapoor-complex-jaipur',
    title: 'Kapoor Residential Complex',
    location: 'Jaipur',
    city: 'jaipur',
    type: 'residential',
    typeLabel: 'Residential',
    area: 18000,
    budget: '₹7.2 Cr',
    duration: '30 months',
    quality: 'Standard',
    year: 2023,
    status: 'completed',
    rating: 5,
    color: '#B87333',
    client: 'Kapoor Builders',
    desc: "A 24-unit residential apartment complex with basement parking, clubhouse, children's play area, and 24/7 security.",
    highlights: ['24 Apartments', 'Basement Parking', 'Clubhouse', "Children's Play Area", '24/7 Security'],
    testimonial: 'Our most ambitious project and BuildRight handled it flawlessly. All units sold before completion.',
  },
];

export const PROJECT_TYPES = [
  { value: 'all',         label: 'All Projects' },
  { value: 'residential', label: 'Residential' },
  { value: 'commercial',  label: 'Commercial' },
  { value: 'retail',      label: 'Retail' },
  { value: 'renovation',  label: 'Renovation' },
];

export const PROJECT_CITIES = [
  { value: 'all',       label: 'All Cities' },
  { value: 'delhi',     label: 'Delhi' },
  { value: 'pune',      label: 'Pune' },
  { value: 'bangalore', label: 'Bangalore' },
  { value: 'bhopal',    label: 'Bhopal' },
  { value: 'indore',    label: 'Indore' },
  { value: 'ahmedabad', label: 'Ahmedabad' },
  { value: 'lucknow',   label: 'Lucknow' },
  { value: 'jaipur',    label: 'Jaipur' },
];

export function getProjectBySlug(slug) {
  return PROJECTS.find(p => p.slug === slug) || null;
}